language: generic
sudo: require
services:
  - docker

before_install:
  - docker build -t frontend:dev -f Dockerfile.dev .

script:
  #- docker run -e CI=true frontend:dev npm run test
  - docker run frontend:dev npm run test -- --coverage
 
